Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
[GCC 5.2.1 20151010] on linux
Type "copyright", "credits" or "license()" for more information.
>>> from mcpi.minecraft import Minecraft
>>> mc = Minecraft.create()
>>> pos1 = mc.player.getTilePos()
>>> pos1 = mc.player.getTilePos()
>>> pos2 = mc.player.getTilePos()
>>> mc.setBlocks(pos1.x, pos1.y, pos1.z, pos2.x, pos2.y, pos2.z, 3)
>>> pos1 = mc.player.getTilePos()
>>> pos2 = mc.player.getTilePos()
>>> mc.setBlocks(pos1.x, pos1.y, pos1.z, pos2.x, pos2.y, pos2.z, 3)
>>> pos1 = mc.player.getTilePos()
>>> pos2 = mc.player.getTilePos()
>>> pos2 = mc.player.getTilePos()
>>> mc.setBlocks(pos1.x, pos1.y, pos1.z, pos2.x, pos2.y, pos2.z, 3)
>>> pos1 = mc.player.getTilePos()
>>> pos2 = mc.player.getTilePos()
>>> mc.setBlocks(pos1.x, pos1.y, pos1.z, pos2.x, pos2.y, pos2.z, 3)
>>> pos1 = mc.player.getTilePos()
>>> pos2 = mc.player.getTilePos()
>>> mc.setBlocks(pos1.x, pos1.y, pos1.z, pos2.x, pos2.y, pos2.z, 3)
>>> home = mc.player.getTilePos()
>>> farm =mc.player.getTilePos()
>>> mc.player.setTilePos(home)
>>> mc.player.setTilePos(farm)
>>> mc.player.setTilePos(home)
>>> pos1 = mc.player.getTilePos()
>>> pos2 = mc.player.getTilePos()
>>> mc.setBlocks(pos1.x, pos1.y, pos1.z, pos2.x, pos2.y, pos2.z, 3)
>>> 
mc.player.setTilePos(farm)
>>> pos1 = mc.player.getTilePos()
>>> pos2 = mc.player.getTilePos()
>>> mc.setBlocks(pos1.x, pos1.y, pos1.z, pos2.x, pos2.y, pos2.z, 3)
>>> print(home)
Vec3(-190,66,356)
>>> print(farm)
Vec3(-169,64,267)
>>> 
